###api


###Signup
GET http://localhost:9092/admin/auth/register-admin
content-type: application/json

{
  "firstName": "wannipa",
  "lastName": "sakprom",
  "email": "wannipasakprom2547@gmail.com",
  "password": "VV137084vv",
  "confirmPassword": "VV137084vv"
}                                    

###login
POST http://localhost:9092/admin/login
content-type: application/json

{
  "email": "wannipasakprom2547@gmail.com",
  "password": "VV137084vv",
  "rememberMe": "false"
}

###profile
GET http://localhost:9092/admin/me
Authorization: Bearer {{login.response.body.$.data.token}}

###forgot
POST http://localhost:9092/admin/forgot-password
content-type: application/json

{
  "email": "wannipasakprom2547@gmail.com"
}

# ==========================================
# USER
# ==========================================

###user-register
POST http://localhost:9092/api/auth/local/register
content-type: application/json

{
  "username": "wewilly",
  "email": "wewilly7084@gmail.com",
  "password": "wewilly04"
}

###user-login
POST http://localhost:9092/api/auth/local
content-type: application/json

{
  "identifier": "wewilly7084@gmail.com",
  "password": "wewilly04"
}

###user-profile
GET http://localhost:9092/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzg4MjUyODIyLCJleHAiOjE3OTA4NDQ4MjJ9.9BhYBjHpi-3zdWjCZMfK8Qlw2HM1u1L2QHQBC2_Zops

###user-forgot
POST http://localhost:9092/api/auth/forgot-password
content-type: application/json

{
  "email": "wannipasakprom2547@gmail.com"
}