services:
  db:
    image: postgres:16-alpine
    container_name: 69-s2-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    container_name: 69-s2-admin
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASS}
    volumes:
      - ./data/admin:/var/lib/pgadmin
    depends_on:
      - db

  app:
    image: prawee/strapi
    container_name: 69-s2-app
    ports:
      - "9092:1337"
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASS}
      - DATABASE_SSL=false
      - JWT_SECRET=${APP_JWT_SECRET}
      - ADMIN_JWT_SECRET=${APP_ADMIN_JWT_SECRET}
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${APP_API_TOKEN_SALT}
      - TRANSFER_TOKEN_SALT=${APP_TRANSFER_TOKEN_SALT}
    depends_on:
      - db

